### ISSUE TITLE
Issue Building the Demonstration

### ISSUE THREAD

**Issue by mcbroster** [clivezhg/select2-to-tree#10]
I have started a new asp empty web form project, and despite following your usage guide to a tee (I hope), I seem to continuously run into errors. Despite the error talking about the dropdown, looking in the inspector seems to indicate the s2data is not actually defined properly. I have touched nothing expect for creating the html element,  JS array, and JS select2totree initializing line, as shown on your guide, as well as the proper file references for jquery and so on. 

![code](https://user-images.githubusercontent.com/16598136/42393475-b9c31c60-8113-11e8-9329-fb741dea116d.png)

The error occurs upon clicking on the select2totree, and its detailed in the picture. There is the fact that Visual Studio seems to enjoy shoving a bunch of default files into the project, so if anything in the solution needs more detail let me know. 

![error](https://user-images.githubusercontent.com/16598136/42393493-c952e732-8113-11e8-9a31-a27c66b46507.png)

![project](https://user-images.githubusercontent.com/16598136/42393497-cbdac506-8113-11e8-9a5b-f44138b4fbe4.png)

If you could help to identify where I've gone wrong, it would be much appreciated.

**Comment by clivezhg** [comment]
Sorry, because I don't use the Visual Studio, I'm not able to reproduce the issue.
Could you build the project into a package, which can be opened by a browser, and post it, then I can try to figure it out.
(BTW, could you try to build a project with select2 only, to verity if it's a select2 issue)

**Comment by mcbroster** [comment]
Thank you for getting back to me. 

In the process of rebuilding this project and the resulting issue, by defaulting to the newest versions of all software involved I managed to get the demo working.

Thanks for your time, and if any other issues appear I'll be sure to let you know.
